name: Build

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci --ignore-scripts

      - run: make code
      - run: make test
      - run: make build

  execute:
    name: Execute
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - id: action
        uses: ./
        with:
          version: 'refs/tags/v1.2.3'

      - run: echo "version: ${{ steps.action.outputs.version }}"
      - run: echo "major: ${{ steps.action.outputs.major }}"
      - run: echo "minor: ${{ steps.action.outputs.minor }}"
      - run: echo "patch: ${{ steps.action.outputs.patch }}"
      - run: echo "prerelease: ${{ steps.action.outputs.prerelease }}"
      - run: echo "build: ${{ steps.action.outputs.build }}"
